//---------------------------------------------------------------------------

#ifndef cmdsH
#define cmdsH
//---------------------------------------------------------------------------

/* length of the command */
/* note: check that these values are correct because if they are'nt will the
   communication wrong */
	const int	lenCmd = 512;
	const int	lenGetCmd = 8;
	/*const int	lenSystemReset = 9;
	const int	lenClearPowerResetFlag = 9;
	const int	lenRemoteAlarmReset = 9;
	const int	lenConfirmClearFunction = 15;
	const int	lenClearintankDeliveryReports = 9;
	const int	lenStartintankLeakDetectTest = 9;
	const int	lenStopintankLeakDetectTest = 9;
	const int	lenDeleteCSLDRateTable = 12;
	const int	lenStartPressureLineLeakTest = 12;
	const int	lenStopPressureLineLeakTest = 12;
	const int	lenStartWPLLDLineLeakTest = 12;
	const int	lenStopWPLLDLineLeakTest = 12;
	const int	lenStartPressureLineLeakTestbyType = 14;
	const int	lenStartWPLLDLineLeakTestbyType = 14;
	const int	lenPressureLineLeakPressureOffsetReset = 12;
	const int	lenWPLLDLineLeakPressureOffsetReset = 12;
	const int	lenCloseCurrentShift = 9;
	const int	lenSystemStatusReport = 9;
	const int	lenSystemConfigurationReport = 9;
	const int	lenPriorityAlarmHistoryReport = 9;
	const int	lenNonPriorityAlarmHistoryReport = 9;
	const int	lenActiveAlarmReport = 9;
	const int	lenClearedAlarmReport = 9;
	const int	lenServiceReportHistory = 9;
	const int	lenintankInventoryReport = 9;
	const int	lenintankDeliveryReport = 9;
	const int	lenintankLeakDetectReport = 9;
	const int	lenintankShiftInventoryReport = 9;
	const int	lenintankStatusReport = 9;
	const int	lenintankAlarmHistoryReport = 9;
	const int	lenintankLeakTestHistoryReport = 9;
	const int	lenintankLeakTestResultsReport = 9;
	const int	lenHRMAdjustedDeliveryReport = 9;
	const int	lenBIRAdjustedDeliveryReport = 9;
	const int	lenintankMostRecentDeliveryReport = 9;
	const int	lenintankStickHeightReport = 9;
	const int	lenTankChartReport = 17;
	const int	lenTicketedDeliveryReport = 11;
	const int	lenPeriodicDeliveryVarianceReport = 11;
	const int	lenWeeklyDeliveryVarianceReport = 11;
	const int	lenDailyDeliveryVarianceReport = 13;
	const int	lenCSLDResultsReport = 9;
	const int	lenFuelManagementReport = 9;
	const int	lenFLSDiagnosticVolumeHistoryTable = 9;
	const int	lenintankStoredInventoryReport = 11;
	const int	lenLiquidSensorStatusReport = 9;
	const int	lenLiquidSensorAlarmHistoryReport = 9;
	const int	lenVaporSensorStatusReport = 9;
	const int	lenVaporSensorAlarmHistoryReport = 9;
	const int	lenGroundwaterSensorStatusReport = 9;
	const int	lenGroundwaterSensorAlarmHistoryReport = 9;
	const int	lenTypeASensorStatusReport = 9;
	const int	lenTypeASensorAlarmHistoryReport = 9;
	const int	lenTypeBSensorStatusReport = 9;
	const int	lenTypeBSensorAlarmHistoryReport = 9;
	const int	lenUniversalSensorStatusReport = 9;
	const int	lenUniversalSensorAlarmHistoryReport = 9;
	const int	lenVolumetricLineLeakResultReport = 9;
	const int	lenVolumetricLineLeakAlarmHistoryReport = 9;
	const int	lenVolumetricLineLeakPumpStatus = 9;
	const int	lenPressureLineLeakTestResults020 = 9;
	const int	lenPressureLineLeakTestHistory020 = 9;
	const int	lenPressureLineLeakStatus = 9;
	const int	lenPressureLineLeakAlarmHistoryReport = 9;
	const int	lenPressureLineLeakTestResults010 = 9;
	const int	lenPressureLineLeakTestHistory010 = 9;
	const int	lenWPLLDLineLeakStatus = 9;
	const int	lenWPLLDLineLeakAlarmHistoryReport = 9;
	const int	lenWPLLDLineLeakTestResults = 9;
	const int	lenWPLLDLineLeakTestHistory = 9;
	const int	lenTankerLoadReport = 9;
	const int	lenInputStatusReport = 9;
	const int	lenInputAlarmHistoryReport = 9;
	const int	lenInputGeneratorAlarmHistoryReport = 9;
	const int	lenRelayStatusReport = 9;
	const int	lenSetTimeofday = 20;
	const int	lenSetShiftStartTime1234 = 13;
	const int	lenSetPrintHeaderLine1234 = 30;
	const int	lenSetSystemRS232SecurityCode = 15;
	const int	lenSetSystemTypeLanguageFlags1 = 11;
	const int	lenSetPeriodicTestNeededWarning = 9;
	const int	lenSetDaysBeforePeriodicTestNeededWarning = 11;
	const int	lenSetDaysBeforePeriodicTestNeededAlarm = 11;
	const int	lenSetAnnualTestNeededWarning = 9;
	const int	lenSetDaysBeforeAnnualTestNeededWarning = 12;
	const int	lenSetDaysBeforeAnnualTestNeededAlarm = 12;
	const int	lenSetRemotePrinterPageEjectFlag = 9;
	const int	lenSetPrintTemperatureCompensationFlag = 9;
	const int	lenSetTemperatureCompensationValue = 17;
	const int	lenSetSystemDateTimeDisplayFormat = 11;
	const int	lenSetBIRShiftPrintoutsFlag = 9;
	const int	lenSetBIRDailyPrintoutsFlag = 9;
	const int	lenSetTankerLoadReportFlag = 9;
	const int	lenSetHProtocolHeightVolumeformat = 9;
	const int	lenSetHRMQPLDMonthlyPrintout = 9;
	const int	lenSetRedirectLocalPrintoutFlag = 9;
	const int	lenSetSystemTypeLanguageFlags15 = 12;
	const int	lenSetSecondaryLanguageCodePageOutput = 10;
	const int	lenSetPLLDWPLLDDurationBeforePrecisionRetest = 12;
	const int	lenSetEnableDisableAutoDaylightSavingTime = 9;
	const int	lenSetStartEndDaylightSavingDateandTime = 17;
	const int	lenSetTicketedDeliveryFlagEnable = 9;
	const int	lenSetTicketedDeliveryTemperatureCompensationFlag = 9;
	const int	lenSetTicketedDeliveryCloseDayofWeek = 9;
	const int	lenSetEuroProtocolPrefix = 9;
	const int	lenSetReceiverAutoDialTypeandStartTimeII = 21;
	const int	lenSetReceiverConfigurationFlag = 9;
	const int	lenSetReceiverLocationLabel = 30;
	const int	lenSetReceiverTelephoneNumber = 30;
	const int	lenSetReceiverDialingDestinationType = 11;
	const int	lenSetReceiverPortNumbertoDial = 9;
	const int	lenSetReceiverRetryNumber = 11;
	const int	lenSetReceiverRetryDelayTime = 11;
	const int	lenSetReceiverConfirmationReportFlag = 9;
	const int	lenSetFaxAutoDialMethod = 9;
	const int	lenSetReceiverReportList = 97;
	const int	lenSetReceiverAutoDialTypeandStartTime = 21;
	const int	lenSetReceiverAutoDialOnAlarms = 20;
	const int	lenAutodialAlarmStatus = 9;
	const int	lenSetDelayforAutodialonAlarmClear = 11;
	const int	lenSetReceiverAlarmStatus = 12;
	const int	lenSetRS232EndofMessage = 9;
	const int	lenSetTicketedVarianceAnalysisPrintoutFlags = 12;
	const int	lenSetTicketedDeliveryBookVariancePrintoutFlags = 12;
	const int	lenSetTicketedDeliveryVariancePrintoutFlags = 12;
	const int	lenSetRS232SecurityCodeperPort = 16;
	const int	lenSetDisplayFormatRS232ETXperPort = 11;
	const int	lenSetComputerFormatRS232ETXperPort = 11;
	const int	lenSetTankPeriodicTestNeededWarning = 9;
	const int	lenSetDaysBeforeTankPeriodicTestNeededWarning = 11;
	const int	lenSetDaysBeforeTankPeriodicTestNeededAlarm = 11;
	const int	lenSetTankAnnualTestNeededWarning = 9;
	const int	lenSetDaysBeforeTankAnnualTestNeededWarning = 12;
	const int	lenSetDaysBeforeTankAnnualTestNeededAlarm = 12;
	const int	lenSetCSLDEvaporationReidVaporPressureChart = 201;
	const int	lenSetLineReEnableMethod = 9;
	const int	lenSetPeriodicLineLeakTestAutoConfirm = 9;
	const int	lenSetAnnualLineLeakTestAutoConfirm = 9;
	const int	lenSetLinePeriodicTestNeededWarning = 9;
	const int	lenSetDaysBeforeLinePeriodicTestNeededWarning = 11;
	const int	lenSetDaysBeforeLinePeriodicTestNeededAlarm = 11;
	const int	lenSetLineAnnualTestNeededWarning = 9;
	const int	lenSetDaysBeforeLineAnnualTestNeededWarning = 12;
	const int	lenSetDaysBeforeLineAnnualTestNeededAlarm = 12;
	const int	lenSetReceiverAutoDialonAlarmII = 17;
	const int	lenSetInventoryRecordTime1234 = 13;
	const int	lenSetTankConfiguration = 25;
	const int	lenSetTankProductLabel = 30;
	const int	lenSetTankProductCode = 9;
	const int	lenSetTank1PointFullHeightVolume = 17;
	const int	lenSetTank4PointFull = 51;
	const int	lenSetTank20PointFull = 150;
	const int	lenSetTankDiameter = 17;
	const int	lenSetTankTilt = 17;
	const int	lenSetTankThermalExpansionCoefficient = 17;
	const int	lenSetTankLinearCalculatedFullVolume = 17;
	const int	lenSetTankStickHeightFunctionEnable = 9;
	const int	lenSetTankStickHeightOffset = 17;
	const int	lenSetTankProgrammableFloatParameters = 41;
	const int	lenSetTankProbeOffset = 17;
	const int	lenSetTankDeliveryDelay = 11;
	const int	lenSetTankLeakTestTypeStartTime = 61;
	const int	lenSetTankManifoldedPartners = 61;
	const int	lenSetCSLDProbabilityofDetection = 9;
	const int	lenSetCSLDClimateFactor = 9;
	const int	lenSetBIRMeterDataPresent = 9;
	const int	lenSetAccuChartUpdateScheduling = 9;
	const int	lenSetTankCSLDEvaporationCompensation = 9;
	const int	lenSetTankStageIIVaporRecovery = 9;
	const int	lenSetintankLeakTestEarlyStop = 9;
	const int	lenSetintankStaticGrossTestAutoConfirm = 9;
	const int	lenSetCSLDReportOnlyMode = 9;
	const int	lenSetTankLowLevelLimit = 17;
	const int	lenSetTankHighLevelLimit = 17;
	const int	lenSetTankOverfillLevelLimit = 17;
	const int	lenSetTankHighWaterLevelLimit = 17;
	const int	lenSetTankSuddenLossLimit = 17;
	const int	lenSetTankLeakAlarmLimit = 17;
	const int	lenSetTankHighWaterWarningLimit = 17;
	const int	lenSetTankMaximumVolumeLimit = 17;
	const int	lenSetTankDeliveryRequiredLimit = 17;
	const int	lenSetTankAnnualLeakTestMinimumVolume = 17;
	const int	lenSetTankLastAnnualTest = 15;
	const int	lenSetTankPeriodicTestType = 9;
	const int	lenSetEnableDisableTankLeakTestFailAlarms = 12;
	const int	lenSetCAP0ProbeConductiveBootFlag = 9;
	const int	lenSetMagProbeFloatSize = 9;
	const int	lenSetTankLeakTestNotify = 9;
	const int	lenSetTankLeakTestAveraging = 11;
	const int	lenSetTankTestSiphonBreak = 9;
	const int	lenSetLeakTestReportType = 9;
	const int	lenSetTankHRMReconciliationWarningLimit = 17;
	const int	lenSetTankHRMReconciliationAlarmLimit = 17;
	const int	lenSetTankPeriodicLeakTestMinimumVolume = 17;
	const int	lenSetTankAccuChartEndShapeTypeandFactor = 18;
	const int	lenSetTankLowLevelThresholdforSequentialLineManifold = 17;
	const int	lenFuelManagementGeneralSetupInquiry = 9;
	const int	lenSetFuelManagementDeliveryNeededWarning = 17;
	const int	lenSetFuelManagementAutomaticReportPrintTime = 13;
	const int	lenSetFuelManagementAverageDailySales = 18;
	const int	lenSetLiquidSensorConfiguration = 9;
	const int	lenSetLiquidSensorLocationLabel = 30;
	const int	lenSetLiquidSensorType = 9;
	const int	lenSetLiquidSensorCategory = 9;
	const int	lenSetVaporSensorConfiguration = 9;
	const int	lenSetVaporSensorLocationLabel = 30;
	const int	lenSetVaporSensorAlarmThreshold = 17;
	const int	lenSetVaporSensorCategory = 9;
	const int	lenSetGroundwaterSensorConfiguration = 9;
	const int	lenSetGroundwaterSensorLocationLabel = 30;
	const int	lenSetGroundwaterSensorCategory = 9;
	const int	lenSetTypeASensorConfiguration = 9;
	const int	lenSetTypeASensorLocationLabel = 30;
	const int	lenSetTypeASensorType = 9;
	const int	lenSetTypeASensorCategory = 9;
	const int	lenSetTypeBSensorConfiguration = 9;
	const int	lenSetTypeBSensorLocationLabel = 30;
	const int	lenSetTypeBSensorType = 9;
	const int	lenSetTypeBSensorCategory = 9;
	const int	lenSetUniversalSensorConfiguration = 9;
	const int	lenSetUniversalSensorLocationLabel = 30;
	const int	lenSetUniversalSensorType = 9;
	const int	lenSetUniversalSensorCategory = 9;
	const int	lenSetVolumetricLineLeakConfiguration = 9;
	const int	lenSetVolumetricLineLeakTankNumber = 11;
	const int	lenSetVolumetricLineLeak2InchPipeLength = 17;
	const int	lenSetVolumetricLineLeak3InchPipeLength = 17;
	const int	lenSetVolumetricLineLeakPumpPSI = 17;
	const int	lenSetVolumetricLineLeakPipingMaterial = 11;
	const int	lenSetVolumetricLineLeakShutdownRate = 11;
	const int	lenSetVolumetricLineLeakPumpSideTest = 11;
	const int	lenSetVolumetricLineLeakTestTypeStartTime = 61;
	const int	lenSetLineLeakLockoutSchedule = 31;
	const int	lenSetLineDisableAlarmAssignments = 17;
	const int	lenSetVolumetricLineLeakLastAnnualTest = 15;
	const int	lenSetVolumetricLineLeakDispenseMode = 9;
	const int	lenSetVolumetricLineLeakFuelType = 11;
	const int	lenSetVolumetricLineLeakWaitMethod = 11;
	const int	lenSetVolumetricLineLeakLocationLabel = 30;
	const int	lenSetVolumetricLineLeakBlendPartner = 11;
	const int	lenSetPumpSensorConfiguration = 9;
	const int	lenSetPumpSensorTankNumber = 11;
	const int	lenSetPumpSensorDispenseMode = 9;
	const int	lenSetPressureLineLeakLowPressureShutoff = 9;
	const int	lenSetPressureLineLeakAltitudePressureOffset = 17;
	const int	lenSetPressureLineLeakSecondaryPipeLength = 17;
	const int	lenPressureLineLeakGeneralSetupInquiry = 9;
	const int	lenSetPressureLineLeakConfiguration = 9;
	const int	lenSetPressureLineLeakLabel = 30;
	const int	lenSetPressureLineLeak010GPHTestSchedule7 = 9;
	const int	lenSetPressureLineLeakShutdownRate = 11;
	const int	lenSetPressureLineLeakTankNumber = 11;
	const int	lenSetPressureLineLeakDispenseMode = 9;
	const int	lenSetPressureLineLeakDisableAlarmAssignments = 17;
	const int	lenSetPressureLineLeakPipingMaterial = 11;
	const int	lenSetPressureLineLeakPrimaryPipeLength = 17;
	const int	lenSetPressureLineLeakSensorType = 9;
	const int	lenSetPressureLineLeak010GPHTestSchedule16 = 13;
	const int	lenSetPressureLineLeak020GPHTestSchedule = 9;
	const int	lenSetPressureLineLeak01GPHAutoTestEnable = 9;
	const int	lenSetPressureLineLeakDispenseThreshold = 17;
	const int	lenDIMSoftwareRevision = 9;
	const int	lenSetMechanicalDispenserinterfaceString = 21;
	const int	lenSetElectronicDispenserinterfaceString = 21;
	const int	lenSetReconciliationAutoDailyClosingTime = 13;
	const int	lenSetAutoShiftClosingTime1234 = 13;
	const int	lenSetPeriodicReconciliationMode = 11;
	const int	lenSetPeriodicReconciliationReportLength = 11;
	const int	lenSetPeriodicReconciliationAlarmFlag = 11;
	const int	lenSetPeriodicReconciliationAlarmThreshold = 17;
	const int	lenSetPeriodicReconciliationAlarmOffset = 17;
	const int	lenSetRemotePrinterReconciliationReportFormat = 11;
	const int	lenSetShiftManualAdjustmentValue = 20;
	const int	lenSetDailyManualAdjustmentValue = 21;
	const int	lenCloseCurrentReconciliationShift = 11;
	const int	lenClearTankMapTable = 12;
	const int	lenSetBIRTemperatureCompensationFlag = 9;
	const int	lenWPLLDLineLeakGeneralSetup = 9;
	const int	lenSetWPLLDLineLeakConfiguration = 9;
	const int	lenSetWPLLDLineLeakLabel = 30;
	const int	lenSetWPLLDLineLeak020GPHTestSchedule = 9;
	const int	lenSetWPLLDLineLeakShutdownRate = 11;
	const int	lenSetWPLLDLineLeakTankNumber = 11;
	const int	lenSetWPLLDLineLeakDispenseMode = 9;
	const int	lenSetWPLLDLineDisableAlarmAssignments = 17;
	const int	lenSetWPLLDLineLeakPipeType = 11;
	const int	lenSetWPLLDLineLeakPipeLength = 17;
	const int	lenSetWPLLDLineLeak010GPHTestSchedule = 13;
	const int	lenSetWPLLDLineLeak010GPHTestScheduleEnable = 9;
	const int	lenSetWPLLDLineLeakSecondaryPipeLength = 17;
	const int	lenSetWPLLDLineLeakAltitudePressureOffset = 17;
	const int	lenSetBIRMeterTankmapping = 21;
	const int	lenSetMeterCalibrationOffset = 17;
	const int	lenSetTicketedDelivery = 113;
	const int	lenSetLineDisableAlarmAssignmentsII = 17;
	const int	lenSetPressureLineDisableAlarmAssignmentsII = 17;
	const int	lenSetWPLLDLineDisableAlarmAssignmentsII = 17;
	const int	lenSetInputConfiguration = 9;
	const int	lenSetInputLocationLabel = 30;
	const int	lenSetInputType = 13;
	const int	lenSetInputDispenseMode = 9;
	const int	lenSetRelayConfiguration = 9;
	const int	lenSetRelayLocationLabel = 30;
	const int	lenSetRelayAlarmAssignments = 17;
	const int	lenSetRelayOrientation = 9;
	const int	lenSetRelayType = 9;
	const int	lenSetRelayTankAssignment = 11;
	const int	lenRestoreAllSetupDatafromEEPROM = 12;
	const int	lenSaveAllSetupDatatoEEPROM = 12;
	const int	lenClearAllSetupDatafromEEPROM = 12;
	const int	lenSetCommunicationPortData = 21;
	const int	lenInitializeCommunicationPortData = 121;
	const int	lenSetSiteLinkModemType = 11;
	const int	lenSetModemSetupString = 30;
	const int	lenSetDialToneValidationinterval = 13;
	const int	lenCommunicationStatusInformation = 9;
	const int	lenDTRNormalStateforSerialSatelliteBoards = 9;
	const int	lenSetAccuChartCalibrationRestart = 12;
	const int	lenSetRelayAlarmAssignmentsII = 17;
	const int	lenSelfTestResultsReport = 9;
	const int	lenSystemRevisionLevelReport = 9;
	const int	lenPCDiagnosticReport = 9;
	const int	lenSystemRevisionLevelReportII = 9;
	const int	lenProbeTypeandSerialNumber = 9;
	const int	lenProbeFactoryDryCalibrationValues = 9;
	const int	lenProbeFactoryWetCalibrationValues = 9;
	const int	lenProbeUpdatedDryCalibrationValues = 9;
	const int	lenProbeUpdatedWetCalibrationValues = 9;
	const int	lenProbeSegmentSensitivityRatios = 9;
	const int	lenProbeLastSampleBuffers = 9;
	const int	lenProbeFastAverageBuffers = 9;
	const int	lenProbeStandardAverageBuffers = 9;
	const int	lenProbeLongTermAverageBuffers = 9;
	const int	lenMagProbeOptionTable = 9;
	const int	lenProbeLeakTestFlagsPresentTest = 9;
	const int	lenProbeLeakTestFlagsStoredTest = 9;
	const int	lenProbeLeakTestFlagsGrossTest = 9;
	const int	lenTankLeakTestAveragingBuffers = 9;
	const int	lenCSLDDiagnosticsRateTable = 9;
	const int	lenCSLDDiagnosticsRateTest = 9;
	const int	lenCSLDDiagnosticsVolumeHistoryTable = 9;
	const int	lenCSLDDiagnosticsMovingAverageTable = 9;
	const int	lenCSLDDiagnosticsLeakTestStatus = 9;
	const int	lenCSLDMonthlyReport = 9;
	const int	lenHRMDiagnosticReport = 9;
	const int	lenHRMDailyHistory = 9;
	const int	lenFuelManagementDiagnosticReport = 9;
	const int	lenPowerOutageDiagnosticReport = 9;
	const int	lenLiquidSensorDiagnosticReport = 9;
	const int	lenVaporSensorDiagnosticReport = 9;
	const int	lenVaporSensorConcentrationReport = 9;
	const int	lenGroundwaterSensorDiagnosticReport = 9;
	const int	lenGroundTemperatureSensorDiagnosticReport = 9;
	const int	lenTypeASensorDiagnosticReport = 9;
	const int	lenTypeBSensorDiagnosticReport = 9;
	const int	lenUniversalSensorDiagnosticReport = 9;
	const int	lenVolumetricLineLeakStatus = 9;
	const int	lenVolumetricLineLeakDiagnosticGrossTestHistory = 9;
	const int	lenVolumetricLineLeak0102GPHDiagnosticHistory = 9;
	const int	lenPumpSensorDiagnostic = 9;
	const int	lenPressureLineLeakPressureOffsetTest = 9;
	const int	lenWPPLDLineLeakPressureOffsetTest = 9;
	const int	lenPressureLineLeakPressureOffsetMonitorReport = 9;
	const int	lenWPLLDLineLeakPressureOffsetMonitorReport = 9;
	const int	lenPressureLineLeakDiagnosticReport = 9;
	const int	lenWPLLDLineLeakDiagnosticReport = 9;
	const int	lenWPLLDLineLeakCommunicationDiagnosticReport = 9;
	const int	lenPressureLineLeak30GPHTestDiagnostic = 9;
	const int	lenPressureLineLeakMidrangeTestDiagnostic = 9;
	const int	lenPressureLineLeak02GPHTestDiagnostic = 9;
	const int	lenPressureLineLeak01GPHTestDiagnostic = 9;
	const int	lenWPLLDLineLeak30GPHTestDiagnostic = 9;
	const int	lenWPLLDLineLeakMidrangeTestDiagnostic = 9;
	const int	lenWPLLDLineLeak02GPHTestDiagnostic = 9;
	const int	lenWPLLDLineLeak01GPHTestDiagnostic = 9;
	const int	lenAccuChartDiagnosticsReport = 9;
	const int	lenAccuChartStatusReport = 9;
	const int	lenAccuChartCalibrationHistoryReport = 9;
	const int	lenMDIMTotalizerReport = 9;
	const int	lenBasicInventoryReconciliationDailyRowReport = 13;
	const int	lenBasicInventoryReconciliationDailyColumnReport = 13;
	const int	lenBasicInventoryReconciliationShiftRowReport = 11;
	const int	lenBasicInventoryReconciliationShiftColumnReport = 11;
	const int	lenBasicInventoryReconciliationPeriodicRowReport106 = 9;
	const int	lenBasicInventoryReconciliationPeriodicColumnReport106 = 9;
	const int	lenBasicInventoryReconciliationPeriodicRowReport114 = 11;
	const int	lenBasicInventoryReconciliationPeriodicColumnReport114 = 11;
	const int	lenIndividualBasicReconciliationDailyHistoryDiagnostic = 9;
	const int	lenPeriodicBookVariance = 11;
	const int	lenWeeklyBookVariance = 11;
	const int	lenDailyBookVariance = 13;
	const int	lenPeriodicVarianceAnalysisReport = 11;
	const int	lenWeeklyVarianceAnalysisReport = 11;
	const int	lenDailyVarianceAnalysisReport = 13;
	const int	lenPeriodicVarianceAnalysisDailyReport = 11;*/

/* command identification number */
	const int	SystemResetID = 0x001;
	const int	ClearPowerResetFlagID = 0x002;
	const int	RemoteAlarmResetID = 0x003;
	const int	ConfirmClearFunctionID = 0x031;
	const int	ClearintankDeliveryReportsID = 0x051;
	const int	StartintankLeakDetectTestID = 0x052;
	const int	StopintankLeakDetectTestID = 0x053;
	const int	DeleteCSLDRateTableID = 0x054;
	const int	StartPressureLineLeakTestID = 0x81;
	const int	StopPressureLineLeakTestID = 0x082;
	const int	StartWPLLDLineLeakTestID = 0x083;
	const int	StopWPLLDLineLeakTestID = 0x084;
	const int	StartPressureLineLeakTestbyTypeID = 0x087;
	const int	StartWPLLDLineLeakTestbyTypeID = 0x088;
	const int	PressureLineLeakPressureOffsetResetID = 0x089;
	const int	WPLLDLineLeakPressureOffsetResetID = 0x090;
	const int	CloseCurrentShiftID = 0x091;
	const int	SystemStatusReportID = 0x101;
	const int	SystemConfigurationReportID = 0x102;
	const int	PriorityAlarmHistoryReportID = 0x111;
	const int	NonPriorityAlarmHistoryReportID = 0x112;
	const int	ActiveAlarmReportID = 0x113;
	const int	ClearedAlarmReportID = 0x114;
	const int	ServiceReportHistoryID = 0x116;
	const int	intankInventoryReportID = 0x201;
	const int	intankDeliveryReportID = 0x202;
	const int	intankLeakDetectReportID = 0x203;
	const int	intankShiftInventoryReportID = 0x204;
	const int	intankStatusReportID = 0x205;
	const int	intankAlarmHistoryReportID = 0x206;
	const int	intankLeakTestHistoryReportID = 0x207;
	const int	intankLeakTestResultsReportID = 0x208;
	const int	HRMAdjustedDeliveryReportID = 0x20a;
	const int	BIRAdjustedDeliveryReportID = 0x20b;
	const int	ntankMostRecentDeliveryReportID = 0x20c;
	const int	intankStickHeightReportID = 0x20d;
	const int	TankChartReportID = 0x211;
	const int	TicketedDeliveryReportID = 0x221;
	const int	PeriodicDeliveryVarianceReportID = 0x225;
	const int	WeeklyDeliveryVarianceReportID = 0x226;
	const int	DailyDeliveryVarianceReportID = 0x227;
	const int	CSLDResultsReportID = 0x251;
	const int	FuelManagementReportID = 0x281;
	const int	FLSDiagnosticVolumeHistoryTableID = 0x282;
	const int	intankStoredInventoryReportID = 0x2e2;
	const int	LiquidSensorStatusReportID = 0x301;
	const int	LiquidSensorAlarmHistoryReportID = 0x302;
	const int	VaporSensorStatusReportID = 0x306;
	const int	VaporSensorAlarmHistoryReportID = 0x307;
	const int	GroundwaterSensorStatusReportID = 0x311;
	const int	GroundwaterSensorAlarmHistoryReportID = 0x312;
	const int	TypeASensorStatusReportID = 0x341;
	const int	TypeASensorAlarmHistoryReportID = 0x342;
	const int	TypeBSensorStatusReportID = 0x346;
	const int	TypeBSensorAlarmHistoryReportID = 0x347;
	const int	UniversalSensorStatusReportID = 0x34b;
	const int	UniversalSensorAlarmHistoryReportID = 0x34c;
	const int	VolumetricLineLeakResultReportID = 0x351;
	const int	VolumetricLineLeakAlarmHistoryReportID = 0x352;
	const int	VolumetricLineLeakPumpStatusID = 0x353;
	const int	PressureLineLeakTestResultsID020 = 0x373;
	const int	PressureLineLeakTestHistoryID020 = 0x374;
	const int	PressureLineLeakStatusID = 0x381;
	const int	PressureLineLeakAlarmHistoryReportID = 0x382;
	const int	PressureLineLeakTestResultsID010 = 0x383;
	const int	PressureLineLeakTestHistoryID010 = 0x384;
	const int	WPLLDLineLeakStatusID = 0x386;
	const int	WPLLDLineLeakAlarmHistoryReportID = 0x387;
	const int	WPLLDLineLeakTestResultsID = 0x388;
	const int	WPLLDLineLeakTestHistoryID = 0x389;
	const int	TankerLoadReportID =0x391;
	const int	InputStatusReportID = 0x401;
	const int	InputAlarmHistoryReportID = 0x402;
	const int	InputGeneratorAlarmHistoryReportID = 0x403;
	const int	RelayStatusReportID = 0x406;
	const int	SetTimeofdayID = 0x501;
	const int	SetShiftStartTime1234ID = 0x502;
	const int	SetPrintHeaderLine1234ID = 0x503;
	const int	SetSystemRS232SecurityCodeID = 0x504;
	const int	SetSystemTypeLanguageFlagsID1 = 0x505;
	const int	SetPeriodicTestNeededWarningID = 0x506;
	const int	SetDaysBeforePeriodicTestNeededWarningID = 0x507;
	const int	SetDaysBeforePeriodicTestNeededAlarmID = 0x508;
	const int	SetAnnualTestNeededWarningID = 0x509;
	const int	SetDaysBeforeAnnualTestNeededWarningID = 0x50a;
	const int	SetDaysBeforeAnnualTestNeededAlarmID = 0x50b;
	const int	SetRemotePrinterPageEjectFlagID = 0x50c;
	const int	SetPrintTemperatureCompensationFlagID = 0x50d;
	const int	SetTemperatureCompensationValueID = 0x50e;
	const int	SetSystemDateTimeDisplayFormatID = 0x50f;
	const int	SetBIRShiftPrintoutsFlagID = 0x511;
	const int	SetBIRDailyPrintoutsFlagID = 0x512;
	const int	SetTankerLoadReportFlagID = 0x513;
	const int	SetHProtocolHeightVolumeformatID = 0x514;
	const int	SetHRMQPLDMonthlyPrintoutID = 0x515;
	const int	SetRedirectLocalPrintoutFlagID = 0x516;
	const int	SetSystemTypeLanguageFlagsID15 = 0x517;
	const int	SetSecondaryLanguageCodePageOutputID = 0x518;
	const int	SetPLLDWPLLDDurationBeforePrecisionRetestID = 0x519;
	const int	SetEnableDisableAutoDaylightSavingTimeID = 0x51a;
	const int	SetStartEndDaylightSavingDateandTimeID = 0x51b;
	const int	SetTicketedDeliveryFlagEnableID = 0x51c;
	const int	SetTicketedDeliveryTemperatureCompensationFlagID = 0x51d;
	const int	SetTicketedDeliveryCloseDayofWeekID = 0x51e;
	const int	SetEuroProtocolPrefixID = 0x51f;
	const int	SetReceiverAutoDialTypeandStartTimeIIID = 0x520;
	const int	SetReceiverConfigurationFlagID = 0x521;
	const int	SetReceiverLocationLabelID = 0x522;
	const int	SetReceiverTelephoneNumberID = 0x523;
	const int	SetReceiverDialingDestinationTypeID = 0x524;
	const int	SetReceiverPortNumbertoDialID = 0x525;
	const int	SetReceiverRetryNumberID = 0x526;
	const int	SetReceiverRetryDelayTimeID = 0x527;
	const int	SetReceiverConfirmationReportFlagID = 0x528;
	const int	SetFaxAutoDialMethodID = 0x529;
	const int	SetReceiverReportListID = 0x52a;
	const int	SetReceiverAutoDialTypeandStartTimeID = 0x52b;
	const int	SetReceiverAutoDialOnAlarmsID = 0x52c;
	const int	AutodialAlarmStatusID = 0x52d;
	const int	SetDelayforAutodialonAlarmClearID = 0x52e;
	const int	SetReceiverAlarmStatusID = 0x52f;
	const int	SetRS232EndofMessageID = 0x531;
	const int	SetTicketedVarianceAnalysisPrintoutFlagsID = 0x532;
	const int	SetTicketedDeliveryBookVariancePrintoutFlagsID = 0x533;
	const int	SetTicketedDeliveryVariancePrintoutFlagsID = 0x534;
	const int	SetRS232SecurityCodeperPortID = 0x536;
	const int	SetDisplayFormatRS232ETXperPortID = 0x537;
	const int	SetComputerFormatRS232ETXperPortID = 0x538;
	const int	SetTankPeriodicTestNeededWarningID = 0x546;
	const int	SetDaysBeforeTankPeriodicTestNeededWarningID = 0x547;
	const int	SetDaysBeforeTankPeriodicTestNeededAlarmID = 0x548;
	const int	SetTankAnnualTestNeededWarningID = 0x549;
	const int	SetDaysBeforeTankAnnualTestNeededWarningID = 0x54a;
	const int	SetDaysBeforeTankAnnualTestNeededAlarmID = 0x54b;
	const int	SetCSLDEvaporationReidVaporPressureChartID = 0x54c;
	const int	SetLineReEnableMethodID = 0x553;
	const int	SetPeriodicLineLeakTestAutoConfirmID = 0x554;
	const int	SetAnnualLineLeakTestAutoConfirmID = 0x555;
	const int	SetLinePeriodicTestNeededWarningID = 0x556;
	const int	SetDaysBeforeLinePeriodicTestNeededWarningID = 0x557;
	const int	SetDaysBeforeLinePeriodicTestNeededAlarmID = 0x558;
	const int	SetLineAnnualTestNeededWarningID = 0x559;
	const int	SetDaysBeforeLineAnnualTestNeededWarningID = 0x55a;
	const int	SetDaysBeforeLineAnnualTestNeededAlarmID = 0x55b;
	const int	SetReceiverAutoDialonAlarmIIID = 0x5bc;
	const int	SetInventoryRecordTime1234ID = 0x5e2;
	const int	SetTankConfigurationID = 0x601;
	const int	SetTankProductLabelID = 0x602;
	const int	SetTankProductCodeID = 0x603;
	const int	SetTank1PointFullHeightVolumeID = 0x604;
	const int	SetTank4PointFullID = 0x605;
	const int	SetTank20PointFullID = 0x606;
	const int	SetTankDiameterID = 0x607;
	const int	SetTankTiltID = 0x608;
	const int	SetTankThermalExpansionCoefficientID = 0x609;
	const int	SetTankLinearCalculatedFullVolumeID = 0x60a;
	const int	SetTankStickHeightFunctionEnableID = 0x60b;
	const int	SetTankStickHeightOffsetID = 0x60c;
	const int	SetTankProgrammableFloatParametersID = 0x60e;
	const int	SetTankProbeOffsetID = 0x60f;
	const int	SetTankDeliveryDelayID = 0x610;
	const int	SetTankLeakTestTypeStartTimeID = 0x611;
	const int	SetTankManifoldedPartnersID = 0x612;
	const int	SetCSLDProbabilityofDetectionID = 0x613;
	const int	SetCSLDClimateFactorID = 0x614;
	const int	SetBIRMeterDataPresentID = 0x615;
	const int	SetAccuChartUpdateSchedulingID = 0x616;
	const int	SetTankCSLDEvaporationCompensationID = 0x618;
	const int	SetTankStageIIVaporRecoveryID = 0x619;
	const int	SetintankLeakTestEarlyStopID = 0x61a;
	const int	SetintankStaticGrossTestAutoConfirmID = 0x61b;
	const int	SetCSLDReportOnlyModeID = 0x61c;
	const int	SetTankLowLevelLimitID = 0x621;
	const int	SetTankHighLevelLimitID = 0x622;
	const int	SetTankOverfillLevelLimitID = 0x623;
	const int	SetTankHighWaterLevelLimitID = 0x624;
	const int	SetTankSuddenLossLimitID = 0x625;
	const int	SetTankLeakAlarmLimitID = 0x626;
	const int	SetTankHighWaterWarningLimitID = 0x627;
	const int	SetTankMaximumVolumeLimitID = 0x628;
	const int	SetTankDeliveryRequiredLimitID = 0x629;
	const int	SetTankAnnualLeakTestMinimumVolumeID = 0x62a;
	const int	SetTankLastAnnualTestID = 0x62b;
	const int	SetTankPeriodicTestTypeID = 0x62c;
	const int	SetEnableDisableTankLeakTestFailAlarmsID = 0x62d;
	const int	SetCAP0ProbeConductiveBootFlagID = 0x62e;
	const int	SetMagProbeFloatSizeID = 0x62f;
	const int	SetTankLeakTestNotifyID = 0x630;
	const int	SetTankLeakTestAveragingID = 0x631;
	const int	SetTankTestSiphonBreakID = 0x632;
	const int	SetLeakTestReportTypeID = 0x633;
	const int	SetTankHRMReconciliationWarningLimitID = 0x634;
	const int	SetTankHRMReconciliationAlarmLimitID = 0x635;
	const int	SetTankPeriodicLeakTestMinimumVolumeID = 0x636;
	const int	SetTankAccuChartEndShapeTypeandFactorID = 0x639;
	const int	SetTankLowLevelThresholdforSequentialLineManifoldID = 0x63a;
	const int	FuelManagementGeneralSetupInquiryID = 0x680;
	const int	SetFuelManagementDeliveryNeededWarningID = 0x681;
	const int	SetFuelManagementAutomaticReportPrintTimeID = 0x682;
	const int	SetFuelManagementAverageDailySalesID = 0x683;
	const int	SetLiquidSensorConfigurationID = 0x701;
	const int	SetLiquidSensorLocationLabelID = 0x702;
	const int	SetLiquidSensorTypeID = 0x703;
	const int	SetLiquidSensorCategoryID = 0x704;
	const int	SetVaporSensorConfigurationID = 0x706;
	const int	SetVaporSensorLocationLabelID = 0x707;
	const int	SetVaporSensorAlarmThresholdID = 0x708;
	const int	SetVaporSensorCategoryID = 0x709;
	const int	SetGroundwaterSensorConfigurationID = 0x711;
	const int	SetGroundwaterSensorLocationLabelID = 0x712;
	const int	SetGroundwaterSensorCategoryID = 0x713;
	const int	SetTypeASensorConfigurationID = 0x741;
	const int	SetTypeASensorLocationLabelID = 0x742;
	const int	SetTypeASensorTypeID = 0x743;
	const int	SetTypeASensorCategoryID = 0x744;
	const int	SetTypeBSensorConfigurationID = 0x746;
	const int	SetTypeBSensorLocationLabelID = 0x747;
	const int	SetTypeBSensorTypeID = 0x748;
	const int	SetTypeBSensorCategoryID = 0x749;
	const int	SetUniversalSensorConfigurationID = 0x74b;
	const int	SetUniversalSensorLocationLabelID = 0x74c;
	const int	SetUniversalSensorTypeID = 0x74d;
	const int	SetUniversalSensorCategoryID = 0x74e;
	const int	SetVolumetricLineLeakConfigurationID = 0x751;
	const int	SetVolumetricLineLeakTankNumberID = 0x752;
	const int	SetVolumetricLineLeak2InchPipeLengthID = 0x753;
	const int	SetVolumetricLineLeak3InchPipeLengthID = 0x754;
	const int	SetVolumetricLineLeakPumpPSIID = 0x755;
	const int	SetVolumetricLineLeakPipingMaterialID = 0x756;
	const int	SetVolumetricLineLeakShutdownRateID = 0x757;
	const int	SetVolumetricLineLeakPumpSideTestID = 0x758;
	const int	SetVolumetricLineLeakTestTypeStartTimeID = 0x759;
	const int	SetLineLeakLockoutScheduleID = 0x75a;
	const int	SetLineDisableAlarmAssignmentsID = 0x75b;
	const int	SetVolumetricLineLeakLastAnnualTestID = 0x75c;
	const int	SetVolumetricLineLeakDispenseModeID = 0x75d;
	const int	SetVolumetricLineLeakFuelTypeID = 0x75e;
	const int	SetVolumetricLineLeakWaitMethodID = 0x75f;
	const int	SetVolumetricLineLeakLocationLabelID = 0x760;
	const int	SetVolumetricLineLeakBlendPartnerID = 0x761;
	const int	SetPumpSensorConfigurationID = 0x771;
	const int	SetPumpSensorTankNumberID = 0x772;
	const int	SetPumpSensorDispenseModeID = 0x773;
	const int	SetPressureLineLeakLowPressureShutoffID = 0x77c;
	const int	SetPressureLineLeakAltitudePressureOffsetID = 0x77d;
	const int	SetPressureLineLeakSecondaryPipeLengthID = 0x77f;
	const int	PressureLineLeakGeneralSetupInquiryID = 0x780;
	const int	SetPressureLineLeakConfigurationID = 0x781;
	const int	SetPressureLineLeakLabelID = 0x782;
	const int	SetPressureLineLeak010GPHTestScheduleID7 = 0x783;
	const int	SetPressureLineLeakShutdownRateID = 0x784;
	const int	SetPressureLineLeakTankNumberID = 0x785;
	const int	SetPressureLineLeakDispenseModeID = 0x786;
	const int	SetPressureLineLeakDisableAlarmAssignmentsID = 0x787;
	const int	SetPressureLineLeakPipingMaterialID = 0x788;
	const int	SetPressureLineLeakPrimaryPipeLengthID = 0x789;
	const int	SetPressureLineLeakSensorTypeID = 0x78a;
	const int	SetPressureLineLeak010GPHTestScheduleID16 = 0x78b;
	const int	SetPressureLineLeak020GPHTestScheduleID = 0x78c;
	const int	SetPressureLineLeak01GPHAutoTestEnableID = 0x78e;
	const int	SetPressureLineLeakDispenseThresholdID = 0x78f;
	const int	DIMSoftwareRevisionID = 0x790;
	const int	SetMechanicalDispenserinterfaceStringID = 0x791;
	const int	SetElectronicDispenserinterfaceStringID = 0x792;
	const int	SetReconciliationAutoDailyClosingTimeID = 0x793;
	const int	SetAutoShiftClosingTime1234ID = 0x794;
	const int	SetPeriodicReconciliationModeID = 0x795;
	const int	SetPeriodicReconciliationReportLengthID = 0x796;
	const int	SetPeriodicReconciliationAlarmFlagID = 0x797;
	const int	SetPeriodicReconciliationAlarmThresholdID = 0x798;
	const int	SetPeriodicReconciliationAlarmOffsetID = 0x799;
	const int	SetRemotePrinterReconciliationReportFormatID = 0x79a;
	const int	SetShiftManualAdjustmentValueID = 0x79b;
	const int	SetDailyManualAdjustmentValueID = 0x79c;
	const int	CloseCurrentReconciliationShiftID = 0x79d;
	const int	ClearTankMapTableID = 0x79e;
	const int	SetBIRTemperatureCompensationFlagID = 0x79f;
	const int	WPLLDLineLeakGeneralSetupID = 0x7a0;
	const int	SetWPLLDLineLeakConfigurationID = 0x7a1;
	const int	SetWPLLDLineLeakLabelID = 0x7a2;
	const int	SetWPLLDLineLeak020GPHTestScheduleID = 0x7a3;
	const int	SetWPLLDLineLeakShutdownRateID = 0x7a4;
	const int	SetWPLLDLineLeakTankNumberID = 0x7a5;
	const int	SetWPLLDLineLeakDispenseModeID = 0x7a6;
	const int	SetWPLLDLineDisableAlarmAssignmentsID = 0x7a7;
	const int	SetWPLLDLineLeakPipeTypeID = 0x7a8;
	const int	SetWPLLDLineLeakPipeLengthID = 0x7a9;
	const int	SetWPLLDLineLeak010GPHTestScheduleID = 0x7aa;
	const int	SetWPLLDLineLeak010GPHTestScheduleEnableID = 0x7ac;
	const int	SetWPLLDLineLeakSecondaryPipeLengthID = 0x7ad;
	const int	SetWPLLDLineLeakAltitudePressureOffsetID = 0x7af;
	const int	SetBIRMeterTankmappingID = 0x7b1;
	const int	SetMeterCalibrationOffsetID = 0x7b2;
	const int	SetTicketedDeliveryID = 0x7b5;
	const int	SetLineDisableAlarmAssignmentsIIID = 0x7bc;
	const int	SetPressureLineDisableAlarmAssignmentsIIID = 0x7bd;
	const int	SetWPLLDLineDisableAlarmAssignmentsIIID = 0x7be;
	const int	SetInputConfigurationID = 0x801;
	const int	SetInputLocationLabelID = 0x802;
	const int	SetInputTypeID = 0x803;
	const int	SetInputDispenseModeID = 0x804;
	const int	SetRelayConfigurationID = 0x806;
	const int	SetRelayLocationLabelID = 0x807;
	const int	SetRelayAlarmAssignmentsID = 0x808;
	const int	SetRelayOrientationID = 0x809;
	const int	SetRelayTypeID = 0x80a;
	const int	SetRelayTankAssignmentID = 0x80b;
	const int	RestoreAllSetupDatafromEEPROMID = 0x851;
	const int	SaveAllSetupDatatoEEPROMID = 0x852;
	const int	ClearAllSetupDatafromEEPROMID = 0x853;
	const int	SetCommunicationPortDataID = 0x881;
	const int	InitializeCommunicationPortDataID = 0x882;
	const int	SetSiteLinkModemTypeID = 0x885;
	const int	SetModemSetupStringID = 0x886;
	const int	SetDialToneValidationintervalID = 0x887;
	const int	CommunicationStatusInformationID = 0x888;
	const int	DTRNormalStateforSerialSatelliteBoardsID = 0x889;
	const int	SetAccuChartCalibrationRestartID = 0x891;
	const int	SetRelayAlarmAssignmentsIIID = 0x8bc;
	const int	SelfTestResultsReportID = 0x901;
	const int	SystemRevisionLevelReportID = 0x902;
	const int	PCDiagnosticReportID = 0x903;
	const int	SystemRevisionLevelReportIIID = 0x905;
	const int	ProbeTypeandSerialNumberID = 0xa01;
	const int	ProbeFactoryDryCalibrationValuesID = 0xa02;
	const int	ProbeFactoryWetCalibrationValuesID = 0xa03;
	const int	ProbeUpdatedDryCalibrationValuesID = 0xa04;
	const int	ProbeUpdatedWetCalibrationValuesID = 0xa05;
	const int	ProbeSegmentSensitivityRatiosID = 0xa06;
	const int	ProbeLastSampleBuffersID = 0xa10;
	const int	ProbeFastAverageBuffersID = 0xa11;
	const int	ProbeStandardAverageBuffersID = 0xa12;
	const int	ProbeLongTermAverageBuffersID = 0xa13;
	const int	MagProbeOptionTableID = 0xa14;
	const int	ProbeLeakTestFlagsPresentTestID = 0xa20;
	const int	ProbeLeakTestFlagsStoredTestID = 0xa21;
	const int	ProbeLeakTestFlagsGrossTestID = 0xa22;
	const int	TankLeakTestAveragingBuffersID = 0xa23;
	const int	CSLDDiagnosticsRateTableID = 0xa51;
	const int	CSLDDiagnosticsRateTestID = 0xa52;
	const int	CSLDDiagnosticsVolumeHistoryTableID = 0xa53;
	const int	CSLDDiagnosticsMovingAverageTableID = 0xa54;
	const int	CSLDDiagnosticsLeakTestStatusID = 0xa55;
	const int	CSLDMonthlyReportID = 0xa56;
	const int	HRMDiagnosticReportID = 0xa61;
	const int	HRMDailyHistoryID = 0xa62;
	const int	FuelManagementDiagnosticReportID = 0xa81;
	const int	PowerOutageDiagnosticReportID = 0xa91;
	const int	LiquidSensorDiagnosticReportID = 0xb01;
	const int	VaporSensorDiagnosticReportID = 0xb06;
	const int	VaporSensorConcentrationReportID = 0xb07;
	const int	GroundwaterSensorDiagnosticReportID = 0xb11;
	const int	GroundTemperatureSensorDiagnosticReportID = 0xb21;
	const int	TypeASensorDiagnosticReportID = 0xb41;
	const int	TypeBSensorDiagnosticReportID = 0xb46;
	const int	UniversalSensorDiagnosticReportID = 0xb4b;
	const int	VolumetricLineLeakStatusID = 0xb50;
	const int	VolumetricLineLeakDiagnosticGrossTestHistoryID = 0xb51;
	const int	VolumetricLineLeak0102GPHDiagnosticHistoryID = 0xb52;
	const int	PumpSensorDiagnosticID = 0xb71;
	const int	PressureLineLeakPressureOffsetTestID = 0xb7c;
	const int	WPPLDLineLeakPressureOffsetTestID = 0xb7d;
	const int	PressureLineLeakPressureOffsetMonitorReportID = 0xb7e;
	const int	WPLLDLineLeakPressureOffsetMonitorReportID = 0xb7f;
	const int	PressureLineLeakDiagnosticReportID = 0xb81;
	const int	WPLLDLineLeakDiagnosticReportID = 0xb82;
	const int	WPLLDLineLeakCommunicationDiagnosticReportID = 0xb83;
	const int	PressureLineLeak30GPHTestDiagnosticID = 0xb87;
	const int	PressureLineLeakMidrangeTestDiagnosticID = 0xb88;
	const int	PressureLineLeak02GPHTestDiagnosticID = 0xb89;
	const int	PressureLineLeak01GPHTestDiagnosticID = 0xb8a;
	const int	WPLLDLineLeak30GPHTestDiagnosticID = 0xb8b;
	const int	WPLLDLineLeakMidrangeTestDiagnosticID = 0xb8c;
	const int	WPLLDLineLeak02GPHTestDiagnosticID = 0xb8d;
	const int	WPLLDLineLeak01GPHTestDiagnosticID = 0xb8e;
	const int	AccuChartDiagnosticsReportID = 0xb91;
	const int	AccuChartStatusReportID = 0xb93;
	const int	AccuChartCalibrationHistoryReportID = 0xb94;
	const int	MDIMTotalizerReportID = 0xba0;
	const int	BasicInventoryReconciliationDailyRowReportID = 0xc01;
	const int	BasicInventoryReconciliationDailyColumnReportID = 0xc02;
	const int	BasicInventoryReconciliationShiftRowReportID = 0xc03;
	const int	BasicInventoryReconciliationShiftColumnReportID = 0xc04;
	const int	BasicInventoryReconciliationPeriodicRowReportID106 = 0xc05;
	const int	BasicInventoryReconciliationPeriodicColumnReportID106 = 0xc06;
	const int	BasicInventoryReconciliationPeriodicRowReportID114 = 0xc07;
	const int	BasicInventoryReconciliationPeriodicColumnReportID114 = 0xc08;
	const int	IndividualBasicReconciliationDailyHistoryDiagnosticID = 0xc09;
	const int	PeriodicBookVarianceID = 0xc10;
	const int	WeeklyBookVarianceID = 0xc11;
	const int	DailyBookVarianceID = 0xc12;
	const int	PeriodicVarianceAnalysisReportID = 0xc20;
	const int	WeeklyVarianceAnalysisReportID = 0xc21;
	const int	DailyVarianceAnalysisReportID = 0xc22;
	const int	PeriodicVarianceAnalysisDailyReportID = 0xc25;

struct command_strings
{
	/* command string */
	char	cmdSystemReset[lenCmd/*lenSystemReset*/];
	char	cmdClearPowerResetFlag[lenCmd/*lenClearPowerResetFlag*/];
	char	cmdRemoteAlarmReset[lenCmd/*lenRemoteAlarmReset*/];
	char	cmdConfirmClearFunction[lenCmd/*lenConfirmClearFunction*/];
	char	cmdClearInTankDeliveryReports[lenCmd/*lenClearintankDeliveryReports*/];
	char	cmdStartInTankLeakDetectTest[lenCmd/*lenStartintankLeakDetectTest*/];
	char	cmdStopInTankLeakDetectTest[lenCmd/*lenStopintankLeakDetectTest*/];
	char	cmdDeleteCSLDRateTable[lenCmd/*lenDeleteCSLDRateTable*/];
	char	cmdStartPressureLineLeakTest[lenCmd/*lenStartPressureLineLeakTest*/];
	char	cmdStopPressureLineLeakTest[lenCmd/*lenStopPressureLineLeakTest*/];
	char	cmdStartWPLLDLineLeakTest[lenCmd/*lenStartWPLLDLineLeakTest*/];
	char	cmdStopWPLLDLineLeakTest[lenCmd/*lenStopWPLLDLineLeakTest*/];
	char	cmdStartPressureLineLeakTestbyType[lenCmd/*lenStartPressureLineLeakTestbyType*/];
	char	cmdStartWPLLDLineLeakTestbyType[lenCmd/*lenStartWPLLDLineLeakTestbyType*/];
	char	cmdPressureLineLeakPressureOffsetReset[lenCmd/*lenPressureLineLeakPressureOffsetReset*/];
	char	cmdWPLLDLineLeakPressureOffsetReset[lenCmd/*lenWPLLDLineLeakPressureOffsetReset*/];
	char	cmdCloseCurrentShift[lenCmd/*lenCloseCurrentShift*/];
	char	cmdSystemStatusReport[lenCmd/*lenSystemStatusReport*/];
	char	cmdSystemConfigurationReport[lenCmd/*lenSystemConfigurationReport*/];
	char	cmdPriorityAlarmHistoryReport[lenCmd/*lenPriorityAlarmHistoryReport*/];
	char	cmdNonPriorityAlarmHistoryReport[lenCmd/*lenNonPriorityAlarmHistoryReport*/];
	char	cmdActiveAlarmReport[lenCmd/*lenActiveAlarmReport*/];
	char	cmdClearedAlarmReport[lenCmd/*lenClearedAlarmReport*/];
	char	cmdServiceReportHistory[lenCmd/*lenServiceReportHistory*/];
	char	cmdInTankInventoryReport[lenCmd/*lenintankInventoryReport*/];
	char	cmdInTankDeliveryReport[lenCmd/*lenintankDeliveryReport*/];
	char	cmdInTankLeakDetectReport[lenCmd/*lenintankLeakDetectReport*/];
	char	cmdInTankShiftInventoryReport[lenCmd/*lenintankShiftInventoryReport*/];
	char	cmdInTankStatusReport[lenCmd/*lenintankStatusReport*/];
	char	cmdInTankAlarmHistoryReport[lenCmd/*lenintankAlarmHistoryReport*/];
	char	cmdInTankLeakTestHistoryReport[lenCmd/*lenintankLeakTestHistoryReport*/];
	char	cmdInTankLeakTestResultsReport[lenCmd/*lenintankLeakTestResultsReport*/];
	char	cmdHRMAdjustedDeliveryReport[lenCmd/*lenHRMAdjustedDeliveryReport*/];
	char	cmdBIRAdjustedDeliveryReport[lenCmd/*lenBIRAdjustedDeliveryReport*/];
	char	cmdInTankMostRecentDeliveryReport[lenCmd/*lenintankMostRecentDeliveryReport*/];
	char	cmdInTankStickHeightReport[lenCmd/*lenintankStickHeightReport*/];
	char	cmdTankChartReport[lenCmd/*lenTankChartReport*/];
	char	cmdTicketedDeliveryReport[lenCmd/*lenTicketedDeliveryReport*/];
	char	cmdPeriodicDeliveryVarianceReport[lenCmd/*lenPeriodicDeliveryVarianceReport*/];
	char	cmdWeeklyDeliveryVarianceReport[lenCmd/*lenWeeklyDeliveryVarianceReport*/];
	char	cmdDailyDeliveryVarianceReport[lenCmd/*lenDailyDeliveryVarianceReport*/];
	char	cmdCSLDResultsReport[lenCmd/*lenCSLDResultsReport*/];
	char	cmdFuelManagementReport[lenCmd/*lenFuelManagementReport*/];
	char	cmdFLSDiagnosticVolumeHistoryTable[lenCmd/*lenFLSDiagnosticVolumeHistoryTable*/];
	char	cmdInTankStoredInventoryReport[lenCmd/*lenintankStoredInventoryReport*/];
	char	cmdLiquidSensorStatusReport[lenCmd/*lenLiquidSensorStatusReport*/];
	char	cmdLiquidSensorAlarmHistoryReport[lenCmd/*lenLiquidSensorAlarmHistoryReport*/];
	char	cmdVaporSensorStatusReport[lenCmd/*lenVaporSensorStatusReport*/];
	char	cmdVaporSensorAlarmHistoryReport[lenCmd/*lenVaporSensorAlarmHistoryReport*/];
	char	cmdGroundwaterSensorStatusReport[lenCmd/*lenGroundwaterSensorStatusReport*/];
	char	cmdGroundwaterSensorAlarmHistoryReport[lenCmd/*lenGroundwaterSensorAlarmHistoryReport*/];
	char	cmdTypeASensorStatusReport[lenCmd/*lenTypeASensorStatusReport*/];
	char	cmdTypeASensorAlarmHistoryReport[lenCmd/*lenTypeASensorAlarmHistoryReport*/];
	char	cmdTypeBSensorStatusReport[lenCmd/*lenTypeBSensorStatusReport*/];
	char	cmdTypeBSensorAlarmHistoryReport[lenCmd/*lenTypeBSensorAlarmHistoryReport*/];
	char	cmdUniversalSensorStatusReport[lenCmd/*lenUniversalSensorStatusReport*/];
	char	cmdUniversalSensorAlarmHistoryReport[lenCmd/*lenUniversalSensorAlarmHistoryReport*/];
	char	cmdVolumetricLineLeakResultReport[lenCmd/*lenVolumetricLineLeakResultReport*/];
	char	cmdVolumetricLineLeakAlarmHistoryReport[lenCmd/*lenVolumetricLineLeakAlarmHistoryReport*/];
	char	cmdVolumetricLineLeakPumpStatus[lenCmd/*lenVolumetricLineLeakPumpStatus*/];
	char	cmdPressureLineLeakTestResults020[lenCmd/*lenPressureLineLeakTestResults020*/];
	char	cmdPressureLineLeakTestHistory020[lenCmd/*lenPressureLineLeakTestHistory020*/];
	char	cmdPressureLineLeakStatus[lenCmd/*lenPressureLineLeakStatus*/];
	char	cmdPressureLineLeakAlarmHistoryReport[lenCmd/*lenPressureLineLeakAlarmHistoryReport*/];
	char	cmdPressureLineLeakTestResults010[lenCmd/*lenPressureLineLeakTestResults010*/];
	char	cmdPressureLineLeakTestHistory010[lenCmd/*lenPressureLineLeakTestHistory010*/];
	char	cmdWPLLDLineLeakStatus[lenCmd/*lenWPLLDLineLeakStatus*/];
	char	cmdWPLLDLineLeakAlarmHistoryReport[lenCmd/*lenWPLLDLineLeakAlarmHistoryReport*/];
	char	cmdWPLLDLineLeakTestResults[lenCmd/*lenWPLLDLineLeakTestResults*/];
	char	cmdWPLLDLineLeakTestHistory[lenCmd/*lenWPLLDLineLeakTestHistory*/];
	char	cmdTankerLoadReport[lenCmd/*lenTankerLoadReport*/];
	char	cmdInputStatusReport[lenCmd/*lenInputStatusReport*/];
	char	cmdInputAlarmHistoryReport[lenCmd/*lenInputAlarmHistoryReport*/];
	char	cmdInputGeneratorAlarmHistoryReport[lenCmd/*lenInputGeneratorAlarmHistoryReport*/];
	char	cmdRelayStatusReport[lenCmd/*lenRelayStatusReport*/];
	char	cmdSetTimeofday[lenCmd/*lenSetTimeofday*/];
	char	cmdSetShiftStartTime1234[lenCmd/*lenSetShiftStartTime1234*/];
	char	cmdSetPrintHeaderLine1234[lenCmd/*lenSetPrintHeaderLine1234*/];
	char	cmdSetSystemRS232SecurityCode[lenCmd/*lenSetSystemRS232SecurityCode*/];
	char	cmdSetSystemTypeLanguageFlags1[lenCmd/*/*lenSetSystemTypeLanguageFlags1*/];
	char	cmdSetPeriodicTestNeededWarning[lenCmd/*lenSetPeriodicTestNeededWarning*/];
	char	cmdSetDaysBeforePeriodicTestNeededWarning[lenCmd/*lenSetDaysBeforePeriodicTestNeededWarning*/];
	char	cmdSetDaysBeforePeriodicTestNeededAlarm[lenCmd/*lenSetDaysBeforePeriodicTestNeededAlarm*/];
	char	cmdSetAnnualTestNeededWarning[lenCmd/*lenSetAnnualTestNeededWarning*/];
	char	cmdSetDaysBeforeAnnualTestNeededWarning[lenCmd/*lenSetDaysBeforeAnnualTestNeededWarning*/];
	char	cmdSetDaysBeforeAnnualTestNeededAlarm[lenCmd/*lenSetDaysBeforeAnnualTestNeededAlarm*/];
	char	cmdSetRemotePrinterPageEjectFlag[lenCmd/*lenSetRemotePrinterPageEjectFlag*/];
	char	cmdSetPrintTemperatureCompensationFlag[lenCmd/*lenSetPrintTemperatureCompensationFlag*/];
	char	cmdSetTemperatureCompensationValue[lenCmd/*lenSetTemperatureCompensationValue*/];
	char	cmdSetSystemDateTimeDisplayFormat[lenCmd/*lenSetSystemDateTimeDisplayFormat*/];
	char	cmdSetBIRShiftPrintoutsFlag[lenCmd/*lenSetBIRShiftPrintoutsFlag*/];
	char	cmdSetBIRDailyPrintoutsFlag[lenCmd/*lenSetBIRDailyPrintoutsFlag*/];
	char	cmdSetTankerLoadReportFlag[lenCmd/*lenSetTankerLoadReportFlag*/];
	char	cmdSetHProtocolHeightVolumeformat[lenCmd/*lenSetHProtocolHeightVolumeformat*/];
	char	cmdSetHRMQPLDMonthlyPrintout[lenCmd/*lenSetHRMQPLDMonthlyPrintout*/];
	char	cmdSetRedirectLocalPrintoutFlag[lenCmd/*lenSetRedirectLocalPrintoutFlag*/];
	char	cmdSetSystemTypeLanguageFlags15[lenCmd/*lenSetSystemTypeLanguageFlags15*/];
	char	cmdSetSecondaryLanguageCodePageOutput[lenCmd/*lenSetSecondaryLanguageCodePageOutput*/];
	char	cmdSetPLLDWPLLDDurationBeforePrecisionRetest[lenCmd/*lenSetPLLDWPLLDDurationBeforePrecisionRetest*/];
	char	cmdSetEnableDisableAutoDaylightSavingTime[lenCmd/*lenSetEnableDisableAutoDaylightSavingTime*/];
	char	cmdSetStartEndDaylightSavingDateandTime[lenCmd/*lenSetStartEndDaylightSavingDateandTime*/];
	char	cmdSetTicketedDeliveryFlagEnable[lenCmd/*lenSetTicketedDeliveryFlagEnable*/];
	char	cmdSetTicketedDeliveryTemperatureCompensationFlag[lenCmd/*lenSetTicketedDeliveryTemperatureCompensationFlag*/];
	char	cmdSetTicketedDeliveryCloseDayofWeek[lenCmd/*lenSetTicketedDeliveryCloseDayofWeek*/];
	char	cmdSetEuroProtocolPrefix[lenCmd/*lenSetEuroProtocolPrefix*/];
	char	cmdSetReceiverAutoDialTypeandStartTimeII[lenCmd/*lenSetReceiverAutoDialTypeandStartTimeII*/];
	char	cmdSetReceiverConfigurationFlag[lenCmd/*lenSetReceiverConfigurationFlag*/];
	char	cmdSetReceiverLocationLabel[lenCmd/*lenSetReceiverLocationLabel*/];
	char	cmdSetReceiverTelephoneNumber[lenCmd/*lenSetReceiverTelephoneNumber*/];
	char	cmdSetReceiverDialingDestinationType[lenCmd/*lenSetReceiverDialingDestinationType*/];
	char	cmdSetReceiverPortNumbertoDial[lenCmd/*lenSetReceiverPortNumbertoDial*/];
	char	cmdSetReceiverRetryNumber[lenCmd/*lenSetReceiverRetryNumber*/];
	char	cmdSetReceiverRetryDelayTime[lenCmd/*lenSetReceiverRetryDelayTime*/];
	char	cmdSetReceiverConfirmationReportFlag[lenCmd/*lenSetReceiverConfirmationReportFlag*/];
	char	cmdSetFaxAutoDialMethod[lenCmd/*lenSetFaxAutoDialMethod*/];
	char	cmdSetReceiverReportList[lenCmd/*lenSetReceiverReportList*/];
	char	cmdSetReceiverAutoDialTypeandStartTime[lenCmd/*lenSetReceiverAutoDialTypeandStartTime*/];
	char	cmdSetReceiverAutoDialOnAlarms[lenCmd/*lenSetReceiverAutoDialOnAlarms*/];
	char	cmdAutodialAlarmStatus[lenCmd/*lenAutodialAlarmStatus*/];
	char	cmdSetDelayforAutodialonAlarmClear[lenCmd/*lenSetDelayforAutodialonAlarmClear*/];
	char	cmdSetReceiverAlarmStatus[lenCmd/*lenSetReceiverAlarmStatus*/];
	char	cmdSetRS232EndofMessage[lenCmd/*lenSetRS232EndofMessage*/];
	char	cmdSetTicketedVarianceAnalysisPrintoutFlags[lenCmd/*lenSetTicketedVarianceAnalysisPrintoutFlags*/];
	char	cmdSetTicketedDeliveryBookVariancePrintoutFlags[lenCmd/*lenSetTicketedDeliveryBookVariancePrintoutFlags*/];
	char	cmdSetTicketedDeliveryVariancePrintoutFlags[lenCmd/*lenSetTicketedDeliveryVariancePrintoutFlags*/];
	char	cmdSetRS232SecurityCodeperPort[lenCmd/*lenSetRS232SecurityCodeperPort*/];
	char	cmdSetDisplayFormatRS232ETXperPort[lenCmd/*lenSetDisplayFormatRS232ETXperPort*/];
	char	cmdSetComputerFormatRS232ETXperPort[lenCmd/*lenSetComputerFormatRS232ETXperPort*/];
	char	cmdSetTankPeriodicTestNeededWarning[lenCmd/*lenSetTankPeriodicTestNeededWarning*/];
	char	cmdSetDaysBeforeTankPeriodicTestNeededWarning[lenCmd/*lenSetDaysBeforeTankPeriodicTestNeededWarning*/];
	char	cmdSetDaysBeforeTankPeriodicTestNeededAlarm[lenCmd/*lenSetDaysBeforeTankPeriodicTestNeededAlarm*/];
	char	cmdSetTankAnnualTestNeededWarning[lenCmd/*lenSetTankAnnualTestNeededWarning*/];
	char	cmdSetDaysBeforeTankAnnualTestNeededWarning[lenCmd/*lenSetDaysBeforeTankAnnualTestNeededWarning*/];
	char	cmdSetDaysBeforeTankAnnualTestNeededAlarm[lenCmd/*lenSetDaysBeforeTankAnnualTestNeededAlarm*/];
	char	cmdSetCSLDEvaporationReidVaporPressureChart[lenCmd/*lenSetCSLDEvaporationReidVaporPressureChart*/];
	char	cmdSetLineReEnableMethod[lenCmd/*lenSetLineReEnableMethod*/];
	char	cmdSetPeriodicLineLeakTestAutoConfirm[lenCmd/*lenSetPeriodicLineLeakTestAutoConfirm*/];
	char	cmdSetAnnualLineLeakTestAutoConfirm[lenCmd/*lenSetAnnualLineLeakTestAutoConfirm*/];
	char	cmdSetLinePeriodicTestNeededWarning[lenCmd/*lenSetLinePeriodicTestNeededWarning*/];
	char	cmdSetDaysBeforeLinePeriodicTestNeededWarning[lenCmd/*lenSetDaysBeforeLinePeriodicTestNeededWarning*/];
	char	cmdSetDaysBeforeLinePeriodicTestNeededAlarm[lenCmd/*lenSetDaysBeforeLinePeriodicTestNeededAlarm*/];
	char	cmdSetLineAnnualTestNeededWarning[lenCmd/*lenSetLineAnnualTestNeededWarning*/];
	char	cmdSetDaysBeforeLineAnnualTestNeededWarning[lenCmd/*lenSetDaysBeforeLineAnnualTestNeededWarning*/];
	char	cmdSetDaysBeforeLineAnnualTestNeededAlarm[lenCmd/*lenSetDaysBeforeLineAnnualTestNeededAlarm*/];
	char	cmdSetReceiverAutoDialonAlarmII[lenCmd/*lenSetReceiverAutoDialonAlarmII*/];
	char	cmdSetInventoryRecordTime1234[lenCmd/*lenSetInventoryRecordTime1234*/];
	char	cmdSetTankConfiguration[lenCmd/*lenSetTankConfiguration*/];
	char	cmdSetTankProductLabel[lenCmd/*lenSetTankProductLabel*/];
	char	cmdSetTankProductCode[lenCmd/*lenSetTankProductCode*/];
	char	cmdSetTank1PointFullHeightVolume[lenCmd/*lenSetTank1PointFullHeightVolume*/];
	char	cmdSetTank4PointFull[lenCmd/*lenSetTank4PointFull*/];
	char	cmdSetTank20PointFull[lenCmd/*lenSetTank20PointFull*/];
	char	cmdSetTankDiameter[lenCmd/*lenSetTankDiameter*/];
	char	cmdSetTankTilt[lenCmd/*lenSetTankTilt*/];
	char	cmdSetTankThermalExpansionCoefficient[lenCmd/*lenSetTankThermalExpansionCoefficient*/];
	char	cmdSetTankLinearCalculatedFullVolume[lenCmd/*lenSetTankLinearCalculatedFullVolume*/];
	char	cmdSetTankStickHeightFunctionEnable[lenCmd/*lenSetTankStickHeightFunctionEnable*/];
	char	cmdSetTankStickHeightOffset[lenCmd/*lenSetTankStickHeightOffset*/];
	char	cmdSetTankProgrammableFloatParameters[lenCmd/*lenSetTankProgrammableFloatParameters*/];
	char	cmdSetTankProbeOffset[lenCmd/*lenSetTankProbeOffset*/];
	char	cmdSetTankDeliveryDelay[lenCmd/*lenSetTankDeliveryDelay*/];
	char	cmdSetTankLeakTestTypeStartTime[lenCmd/*lenSetTankLeakTestTypeStartTime*/];
	char	cmdSetTankManifoldedPartners[lenCmd/*lenSetTankManifoldedPartners*/];
	char	cmdSetCSLDProbabilityofDetection[lenCmd/*lenSetCSLDProbabilityofDetection*/];
	char	cmdSetCSLDClimateFactor[lenCmd/*lenSetCSLDClimateFactor*/];
	char	cmdSetBIRMeterDataPresent[lenCmd/*lenSetBIRMeterDataPresent*/];
	char	cmdSetAccuChartUpdateScheduling[lenCmd/*lenSetAccuChartUpdateScheduling*/];
	char	cmdSetTankCSLDEvaporationCompensation[lenCmd/*lenSetTankCSLDEvaporationCompensation*/];
	char	cmdSetTankStageIIVaporRecovery[lenCmd/*lenSetTankStageIIVaporRecovery*/];
	char	cmdSetInTankLeakTestEarlyStop[lenCmd/*lenSetintankLeakTestEarlyStop*/];
	char	cmdSetInTankStaticGrossTestAutoConfirm[lenCmd/*lenSetintankStaticGrossTestAutoConfirm*/];
	char	cmdSetCSLDReportOnlyMode[lenCmd/*lenSetCSLDReportOnlyMode*/];
	char	cmdSetTankLowLevelLimit[lenCmd/*lenSetTankLowLevelLimit*/];
	char	cmdSetTankHighLevelLimit[lenCmd/*lenSetTankHighLevelLimit*/];
	char	cmdSetTankOverfillLevelLimit[lenCmd/*lenSetTankOverfillLevelLimit*/];
	char	cmdSetTankHighWaterLevelLimit[lenCmd/*lenSetTankHighWaterLevelLimit*/];
	char	cmdSetTankSuddenLossLimit[lenCmd/*lenSetTankSuddenLossLimit*/];
	char	cmdSetTankLeakAlarmLimit[lenCmd/*lenSetTankLeakAlarmLimit*/];
	char	cmdSetTankHighWaterWarningLimit[lenCmd/*lenSetTankHighWaterWarningLimit*/];
	char	cmdSetTankMaximumVolumeLimit[lenCmd/*lenSetTankMaximumVolumeLimit*/];
	char	cmdSetTankDeliveryRequiredLimit[lenCmd/*lenSetTankDeliveryRequiredLimit*/];
	char	cmdSetTankAnnualLeakTestMinimumVolume[lenCmd/*lenSetTankAnnualLeakTestMinimumVolume*/];
	char	cmdSetTankLastAnnualTest[lenCmd/*lenSetTankLastAnnualTest*/];
	char	cmdSetTankPeriodicTestType[lenCmd/*lenSetTankPeriodicTestType*/];
	char	cmdSetEnableDisableTankLeakTestFailAlarms[lenCmd/*lenSetEnableDisableTankLeakTestFailAlarms*/];
	char	cmdSetCAP0ProbeConductiveBootFlag[lenCmd/*lenSetCAP0ProbeConductiveBootFlag*/];
	char	cmdSetMagProbeFloatSize[lenCmd/*lenSetMagProbeFloatSize*/];
	char	cmdSetTankLeakTestNotify[lenCmd/*lenSetTankLeakTestNotify*/];
	char	cmdSetTankLeakTestAveraging[lenCmd/*lenSetTankLeakTestAveraging*/];
	char	cmdSetTankTestSiphonBreak[lenCmd/*lenSetTankTestSiphonBreak*/];
	char	cmdSetLeakTestReportType[lenCmd/*lenSetLeakTestReportType*/];
	char	cmdSetTankHRMReconciliationWarningLimit[lenCmd/*lenSetTankHRMReconciliationWarningLimit*/];
	char	cmdSetTankHRMReconciliationAlarmLimit[lenCmd/*lenSetTankHRMReconciliationAlarmLimit*/];
	char	cmdSetTankPeriodicLeakTestMinimumVolume[lenCmd/*lenSetTankPeriodicLeakTestMinimumVolume*/];
	char	cmdSetTankAccuChartEndShapeTypeandFactor[lenCmd/*lenSetTankAccuChartEndShapeTypeandFactor*/];
	char	cmdSetTankLowLevelThresholdforSequentialLineManifold[lenCmd/*lenSetTankLowLevelThresholdforSequentialLineManifold*/];
	char	cmdFuelManagementGeneralSetupInquiry[lenCmd/*lenFuelManagementGeneralSetupInquiry*/];
	char	cmdSetFuelManagementDeliveryNeededWarning[lenCmd/*lenSetFuelManagementDeliveryNeededWarning*/];
	char	cmdSetFuelManagementAutomaticReportPrintTime[lenCmd/*lenSetFuelManagementAutomaticReportPrintTime*/];
	char	cmdSetFuelManagementAverageDailySales[lenCmd/*lenSetFuelManagementAverageDailySales*/];
	char	cmdSetLiquidSensorConfiguration[lenCmd/*lenSetLiquidSensorConfiguration*/];
	char	cmdSetLiquidSensorLocationLabel[lenCmd/*lenSetLiquidSensorLocationLabel*/];
	char	cmdSetLiquidSensorType[lenCmd/*lenSetLiquidSensorType*/];
	char	cmdSetLiquidSensorCategory[lenCmd/*lenSetLiquidSensorCategory*/];
	char	cmdSetVaporSensorConfiguration[lenCmd/*lenSetVaporSensorConfiguration*/];
	char	cmdSetVaporSensorLocationLabel[lenCmd/*lenSetVaporSensorLocationLabel*/];
	char	cmdSetVaporSensorAlarmThreshold[lenCmd/*lenSetVaporSensorAlarmThreshold*/];
	char	cmdSetVaporSensorCategory[lenCmd/*lenSetVaporSensorCategory*/];
	char	cmdSetGroundwaterSensorConfiguration[lenCmd/*lenSetGroundwaterSensorConfiguration*/];
	char	cmdSetGroundwaterSensorLocationLabel[lenCmd/*lenSetGroundwaterSensorLocationLabel*/];
	char	cmdSetGroundwaterSensorCategory[lenCmd/*lenSetGroundwaterSensorCategory*/];
	char	cmdSetTypeASensorConfiguration[lenCmd/*lenSetTypeASensorConfiguration*/];
	char	cmdSetTypeASensorLocationLabel[lenCmd/*lenSetTypeASensorLocationLabel*/];
	char	cmdSetTypeASensorType[lenCmd/*lenSetTypeASensorType*/];
	char	cmdSetTypeASensorCategory[lenCmd/*lenSetTypeASensorCategory*/];
	char	cmdSetTypeBSensorConfiguration[lenCmd/*lenSetTypeBSensorConfiguration*/];
	char	cmdSetTypeBSensorLocationLabel[lenCmd/*lenSetTypeBSensorLocationLabel*/];
	char	cmdSetTypeBSensorType[lenCmd/*lenSetTypeBSensorType*/];
	char	cmdSetTypeBSensorCategory[lenCmd/*lenSetTypeBSensorCategory*/];
	char	cmdSetUniversalSensorConfiguration[lenCmd/*lenSetUniversalSensorConfiguration*/];
	char	cmdSetUniversalSensorLocationLabel[lenCmd/*lenSetUniversalSensorLocationLabel*/];
	char	cmdSetUniversalSensorType[lenCmd/*lenSetUniversalSensorType*/];
	char	cmdSetUniversalSensorCategory[lenCmd/*lenSetUniversalSensorCategory*/];
	char	cmdSetVolumetricLineLeakConfiguration[lenCmd/*lenSetVolumetricLineLeakConfiguration*/];
	char	cmdSetVolumetricLineLeakTankNumber[lenCmd/*lenSetVolumetricLineLeakTankNumber*/];
	char	cmdSetVolumetricLineLeak2InchPipeLength[lenCmd/*lenSetVolumetricLineLeak2InchPipeLength*/];
	char	cmdSetVolumetricLineLeak3InchPipeLength[lenCmd/*lenSetVolumetricLineLeak3InchPipeLength*/];
	char	cmdSetVolumetricLineLeakPumpPSI[lenCmd/*lenSetVolumetricLineLeakPumpPSI*/];
	char	cmdSetVolumetricLineLeakPipingMaterial[lenCmd/*lenSetVolumetricLineLeakPipingMaterial*/];
	char	cmdSetVolumetricLineLeakShutdownRate[lenCmd/*lenSetVolumetricLineLeakShutdownRate*/];
	char	cmdSetVolumetricLineLeakPumpSideTest[lenCmd/*lenSetVolumetricLineLeakPumpSideTest*/];
	char	cmdSetVolumetricLineLeakTestTypeStartTime[lenCmd/*lenSetVolumetricLineLeakTestTypeStartTime*/];
	char	cmdSetLineLeakLockoutSchedule[lenCmd/*lenSetLineLeakLockoutSchedule*/];
	char	cmdSetLineDisableAlarmAssignments[lenCmd/*lenSetLineDisableAlarmAssignments*/];
	char	cmdSetVolumetricLineLeakLastAnnualTest[lenCmd/**/];
	char	cmdSetVolumetricLineLeakDispenseMode[lenCmd/*lenSetVolumetricLineLeakLastAnnualTest*/];
	char	cmdSetVolumetricLineLeakFuelType[lenCmd/*lenSetVolumetricLineLeakFuelType*/];
	char	cmdSetVolumetricLineLeakWaitMethod[lenCmd/*lenSetVolumetricLineLeakWaitMethod*/];
	char	cmdSetVolumetricLineLeakLocationLabel[lenCmd/*lenSetVolumetricLineLeakLocationLabel*/];
	char	cmdSetVolumetricLineLeakBlendPartner[lenCmd/*lenSetVolumetricLineLeakBlendPartner*/];
	char	cmdSetPumpSensorConfiguration[lenCmd/*lenSetPumpSensorConfiguration*/];
	char	cmdSetPumpSensorTankNumber[lenCmd/*lenSetPumpSensorTankNumber*/];
	char	cmdSetPumpSensorDispenseMode[lenCmd/*lenSetPumpSensorDispenseMode*/];
	char	cmdSetPressureLineLeakLowPressureShutoff[lenCmd/*lenSetPressureLineLeakLowPressureShutoff*/];
	char	cmdSetPressureLineLeakAltitudePressureOffset[lenCmd/*lenSetPressureLineLeakAltitudePressureOffset*/];
	char	cmdSetPressureLineLeakSecondaryPipeLength[lenCmd/*lenSetPressureLineLeakSecondaryPipeLength*/];
	char	cmdPressureLineLeakGeneralSetupInquiry[lenCmd/*lenPressureLineLeakGeneralSetupInquiry*/];
	char	cmdSetPressureLineLeakConfiguration[lenCmd/*lenSetPressureLineLeakConfiguration*/];
	char	cmdSetPressureLineLeakLabel[lenCmd/*lenSetPressureLineLeakLabel*/];
	char	cmdSetPressureLineLeak010GPHTestSchedule7[lenCmd/*lenSetPressureLineLeak010GPHTestSchedule7*/];
	char	cmdSetPressureLineLeakShutdownRate[lenCmd/*lenSetPressureLineLeakShutdownRate*/];
	char	cmdSetPressureLineLeakTankNumber[lenCmd/*lenSetPressureLineLeakTankNumber*/];
	char	cmdSetPressureLineLeakDispenseMode[lenCmd/*lenSetPressureLineLeakDispenseMode*/];
	char	cmdSetPressureLineLeakDisableAlarmAssignments[lenCmd/*lenSetPressureLineLeakDisableAlarmAssignments*/];
	char	cmdSetPressureLineLeakPipingMaterial[lenCmd/*lenSetPressureLineLeakPipingMaterial*/];
	char	cmdSetPressureLineLeakPrimaryPipeLength[lenCmd/*lenSetPressureLineLeakPrimaryPipeLength*/];
	char	cmdSetPressureLineLeakSensorType[lenCmd/*lenSetPressureLineLeakSensorType*/];
	char	cmdSetPressureLineLeak010GPHTestSchedule16[lenCmd/*lenSetPressureLineLeak010GPHTestSchedule16*/];
	char	cmdSetPressureLineLeak020GPHTestSchedule[lenCmd/*lenSetPressureLineLeak020GPHTestSchedule*/];
	char	cmdSetPressureLineLeak01GPHAutoTestEnable[lenCmd/*lenSetPressureLineLeak01GPHAutoTestEnable*/];
	char	cmdSetPressureLineLeakDispenseThreshold[lenCmd/*lenSetPressureLineLeakDispenseThreshold*/];
	char	cmdDIMSoftwareRevision[lenCmd/*lenDIMSoftwareRevision*/];
	char	cmdSetMechanicalDispenserInterfaceString[lenCmd/*lenSetMechanicalDispenserinterfaceString*/];
	char	cmdSetElectronicDispenserInterfaceString[lenCmd/*lenSetElectronicDispenserinterfaceString*/];
	char	cmdSetReconciliationAutoDailyClosingTime[lenCmd/*lenSetReconciliationAutoDailyClosingTime*/];
	char	cmdSetAutoShiftClosingTime1234[lenCmd/*lenSetAutoShiftClosingTime1234*/];
	char	cmdSetPeriodicReconciliationMode[lenCmd/*lenSetPeriodicReconciliationMode*/];
	char	cmdSetPeriodicReconciliationReportLength[lenCmd/*lenSetPeriodicReconciliationReportLength*/];
	char	cmdSetPeriodicReconciliationAlarmFlag[lenCmd/*lenSetPeriodicReconciliationAlarmFlag*/];
	char	cmdSetPeriodicReconciliationAlarmThreshold[lenCmd/*lenSetPeriodicReconciliationAlarmThreshold*/];
	char	cmdSetPeriodicReconciliationAlarmOffset[lenCmd/*lenSetPeriodicReconciliationAlarmOffset*/];
	char	cmdSetRemotePrinterReconciliationReportFormat[lenCmd/*lenSetRemotePrinterReconciliationReportFormat*/];
	char	cmdSetShiftManualAdjustmentValue[lenCmd/*lenSetShiftManualAdjustmentValue*/];
	char	cmdSetDailyManualAdjustmentValue[lenCmd/*lenSetDailyManualAdjustmentValue*/];
	char	cmdCloseCurrentReconciliationShift[lenCmd/*lenCloseCurrentReconciliationShift*/];
	char	cmdClearTankMapTable[lenCmd/*lenClearTankMapTable*/];
	char	cmdSetBIRTemperatureCompensationFlag[lenCmd/*lenSetBIRTemperatureCompensationFlag*/];
	char	cmdWPLLDLineLeakGeneralSetup[lenCmd/*lenWPLLDLineLeakGeneralSetup*/];
	char	cmdSetWPLLDLineLeakConfiguration[lenCmd/*lenSetWPLLDLineLeakConfiguration*/];
	char	cmdSetWPLLDLineLeakLabel[lenCmd/*lenSetWPLLDLineLeakLabel*/];
	char	cmdSetWPLLDLineLeak020GPHTestSchedule[lenCmd/*lenSetWPLLDLineLeak020GPHTestSchedule*/];
	char	cmdSetWPLLDLineLeakShutdownRate[lenCmd/*lenSetWPLLDLineLeakShutdownRate*/];
	char	cmdSetWPLLDLineLeakTankNumber[lenCmd/*lenSetWPLLDLineLeakTankNumber*/];
	char	cmdSetWPLLDLineLeakDispenseMode[lenCmd/*lenSetWPLLDLineLeakDispenseMode*/];
	char	cmdSetWPLLDLineDisableAlarmAssignments[lenCmd/*lenSetWPLLDLineDisableAlarmAssignments*/];
	char	cmdSetWPLLDLineLeakPipeType[lenCmd/*lenSetWPLLDLineLeakPipeType*/];
	char	cmdSetWPLLDLineLeakPipeLength[lenCmd/*lenSetWPLLDLineLeakPipeLength*/];
	char	cmdSetWPLLDLineLeak010GPHTestSchedule[lenCmd/*lenSetWPLLDLineLeak010GPHTestSchedule*/];
	char	cmdSetWPLLDLineLeak010GPHTestScheduleEnable[lenCmd/*lenSetWPLLDLineLeak010GPHTestScheduleEnable*/];
	char	cmdSetWPLLDLineLeakSecondaryPipeLength[lenCmd/*lenSetWPLLDLineLeakSecondaryPipeLength*/];
	char	cmdSetWPLLDLineLeakAltitudePressureOffset[lenCmd/*lenSetWPLLDLineLeakAltitudePressureOffset*/];
	char	cmdSetBIRMeterTankmapping[lenCmd/*lenSetBIRMeterTankmapping*/];
	char	cmdSetMeterCalibrationOffset[lenCmd/*lenSetMeterCalibrationOffset*/];
	char	cmdSetTicketedDelivery[lenCmd/*lenSetTicketedDelivery*/];
	char	cmdSetLineDisableAlarmAssignmentsII[lenCmd/*lenSetLineDisableAlarmAssignmentsII*/];
	char	cmdSetPressureLineDisableAlarmAssignmentsII[lenCmd/*lenSetPressureLineDisableAlarmAssignmentsII*/];
	char	cmdSetWPLLDLineDisableAlarmAssignmentsII[lenCmd/*lenSetWPLLDLineDisableAlarmAssignmentsII*/];
	char	cmdSetInputConfiguration[lenCmd/*lenSetInputConfiguration*/];
	char	cmdSetInputLocationLabel[lenCmd/*lenSetInputLocationLabel*/];
	char	cmdSetInputType[lenCmd/*lenSetInputType*/];
	char	cmdSetInputDispenseMode[lenCmd/*lenSetInputDispenseMode*/];
	char	cmdSetRelayConfiguration[lenCmd/*lenSetRelayConfiguration*/];
	char	cmdSetRelayLocationLabel[lenCmd/*lenSetRelayLocationLabel*/];
	char	cmdSetRelayAlarmAssignments[lenCmd/*lenSetRelayAlarmAssignments*/];
	char	cmdSetRelayOrientation[lenCmd/*lenSetRelayOrientation*/];
	char	cmdSetRelayType[lenCmd/*lenSetRelayType*/];
	char	cmdSetRelayTankAssignment[lenCmd/*lenSetRelayTankAssignment*/];
	char	cmdRestoreAllSetupDatafromEEPROM[lenCmd/*lenRestoreAllSetupDatafromEEPROM*/];
	char	cmdSaveAllSetupDatatoEEPROM[lenCmd/*lenSaveAllSetupDatatoEEPROM*/];
	char	cmdClearAllSetupDatafromEEPROM[lenCmd/*lenClearAllSetupDatafromEEPROM*/];
	char	cmdSetCommunicationPortData[lenCmd/*lenSetCommunicationPortData*/];
	char	cmdInitializeCommunicationPortData[lenCmd/*lenInitializeCommunicationPortData*/];
	char	cmdSetSiteLinkModemType[lenCmd/*lenSetSiteLinkModemType*/];
	char	cmdSetModemSetupString[lenCmd/*lenSetModemSetupString*/];
	char	cmdSetDialToneValidationInterval[lenCmd/*lenSetDialToneValidationinterval*/];
	char	cmdCommunicationStatusInformation[lenCmd/*lenCommunicationStatusInformation*/];
	char	cmdDTRNormalStateforSerialSatelliteBoards[lenCmd/*lenDTRNormalStateforSerialSatelliteBoards*/];
	char	cmdSetAccuChartCalibrationRestart[lenCmd/*lenSetAccuChartCalibrationRestart*/];
	char	cmdSetRelayAlarmAssignmentsII[lenCmd/*lenSetRelayAlarmAssignmentsII*/];
	char	cmdSelfTestResultsReport[lenCmd/*lenSelfTestResultsReport*/];
	char	cmdSystemRevisionLevelReport[lenCmd/*lenSystemRevisionLevelReport*/];
	char	cmdPCDiagnosticReport[lenCmd/*lenPCDiagnosticReport*/];
	char	cmdSystemRevisionLevelReportII[lenCmd/*lenSystemRevisionLevelReportII*/];
	char	cmdProbeTypeandSerialNumber[lenCmd/*lenProbeTypeandSerialNumber*/];
	char	cmdProbeFactoryDryCalibrationValues[lenCmd/*lenProbeFactoryDryCalibrationValues*/];
	char	cmdProbeFactoryWetCalibrationValues[lenCmd/*lenProbeFactoryWetCalibrationValues*/];
	char	cmdProbeUpdatedDryCalibrationValues[lenCmd/*lenProbeUpdatedDryCalibrationValues*/];
	char	cmdProbeUpdatedWetCalibrationValues[lenCmd/*lenProbeUpdatedWetCalibrationValues*/];
	char	cmdProbeSegmentSensitivityRatios[lenCmd/*lenProbeSegmentSensitivityRatios*/];
	char	cmdProbeLastSampleBuffers[lenCmd/*lenProbeLastSampleBuffers*/];
	char	cmdProbeFastAverageBuffers[lenCmd/*lenProbeFastAverageBuffers*/];
	char	cmdProbeStandardAverageBuffers[lenCmd/*lenProbeStandardAverageBuffers*/];
	char	cmdProbeLongTermAverageBuffers[lenCmd/*lenProbeLongTermAverageBuffers*/];
	char	cmdMagProbeOptionTable[lenCmd/*lenMagProbeOptionTable*/];
	char	cmdProbeLeakTestFlagsPresentTest[lenCmd/*lenProbeLeakTestFlagsPresentTest*/];
	char	cmdProbeLeakTestFlagsStoredTest[lenCmd/*lenProbeLeakTestFlagsStoredTest*/];
	char	cmdProbeLeakTestFlagsGrossTest[lenCmd/*lenProbeLeakTestFlagsGrossTest*/];
	char	cmdTankLeakTestAveragingBuffers[lenCmd/*lenTankLeakTestAveragingBuffers*/];
	char	cmdCSLDDiagnosticsRateTable[lenCmd/*lenCSLDDiagnosticsRateTable*/];
	char	cmdCSLDDiagnosticsRateTest[lenCmd/*lenCSLDDiagnosticsRateTest*/];
	char	cmdCSLDDiagnosticsVolumeHistoryTable[lenCmd/*lenCSLDDiagnosticsVolumeHistoryTable*/];
	char	cmdCSLDDiagnosticsMovingAverageTable[lenCmd/*lenCSLDDiagnosticsMovingAverageTable*/];
	char	cmdCSLDDiagnosticsLeakTestStatus[lenCmd/*lenCSLDDiagnosticsLeakTestStatus*/];
	char	cmdCSLDMonthlyReport[lenCmd/*lenCSLDMonthlyReport*/];
	char	cmdHRMDiagnosticReport[lenCmd/*lenHRMDiagnosticReport*/];
	char	cmdHRMDailyHistory[lenCmd/*lenHRMDailyHistory*/];
	char	cmdFuelManagementDiagnosticReport[lenCmd/*lenFuelManagementDiagnosticReport*/];
	char	cmdPowerOutageDiagnosticReport[lenCmd/*lenPowerOutageDiagnosticReport*/];
	char	cmdLiquidSensorDiagnosticReport[lenCmd/*lenLiquidSensorDiagnosticReport*/];
	char	cmdVaporSensorDiagnosticReport[lenCmd/*lenVaporSensorDiagnosticReport*/];
	char	cmdVaporSensorConcentrationReport[lenCmd/*lenVaporSensorConcentrationReport*/];
	char	cmdGroundwaterSensorDiagnosticReport[lenCmd/*lenGroundwaterSensorDiagnosticReport*/];
	char	cmdGroundTemperatureSensorDiagnosticReport[lenCmd/*lenGroundTemperatureSensorDiagnosticReport*/];
	char	cmdTypeASensorDiagnosticReport[lenCmd/*lenTypeASensorDiagnosticReport*/];
	char	cmdTypeBSensorDiagnosticReport[lenCmd/*lenTypeBSensorDiagnosticReport*/];
	char	cmdUniversalSensorDiagnosticReport[lenCmd/*lenUniversalSensorDiagnosticReport*/];
	char	cmdVolumetricLineLeakStatus[lenCmd/*lenVolumetricLineLeakStatus*/];
	char	cmdVolumetricLineLeakDiagnosticGrossTestHistory[lenCmd/*lenVolumetricLineLeakDiagnosticGrossTestHistory*/];
	char	cmdVolumetricLineLeak0102GPHDiagnosticHistory[lenCmd/*lenVolumetricLineLeak0102GPHDiagnosticHistory*/];
	char	cmdPumpSensorDiagnostic[lenCmd/*lenPumpSensorDiagnostic*/];
	char	cmdPressureLineLeakPressureOffsetTest[lenCmd/*lenPressureLineLeakPressureOffsetTest*/];
	char	cmdWPPLDLineLeakPressureOffsetTest[lenCmd/*lenWPPLDLineLeakPressureOffsetTest*/];
	char	cmdPressureLineLeakPressureOffsetMonitorReport[lenCmd/*lenPressureLineLeakPressureOffsetMonitorReport*/];
	char	cmdWPLLDLineLeakPressureOffsetMonitorReport[lenCmd/*lenWPLLDLineLeakPressureOffsetMonitorReport*/];
	char	cmdPressureLineLeakDiagnosticReport[lenCmd/*lenPressureLineLeakDiagnosticReport*/];
	char	cmdWPLLDLineLeakDiagnosticReport[lenCmd/*lenWPLLDLineLeakDiagnosticReport*/];
	char	cmdWPLLDLineLeakCommunicationDiagnosticReport[lenCmd/*lenWPLLDLineLeakCommunicationDiagnosticReport*/];
	char	cmdPressureLineLeak30GPHTestDiagnostic[lenCmd/*lenPressureLineLeak30GPHTestDiagnostic*/];
	char	cmdPressureLineLeakMidrangeTestDiagnostic[lenCmd/*lenPressureLineLeakMidrangeTestDiagnostic*/];
	char	cmdPressureLineLeak02GPHTestDiagnostic[lenCmd/*lenPressureLineLeak02GPHTestDiagnostic*/];
	char	cmdPressureLineLeak01GPHTestDiagnostic[lenCmd/*lenPressureLineLeak01GPHTestDiagnostic*/];
	char	cmdWPLLDLineLeak30GPHTestDiagnostic[lenCmd/*lenWPLLDLineLeak30GPHTestDiagnostic*/];
	char	cmdWPLLDLineLeakMidrangeTestDiagnostic[lenCmd/*lenWPLLDLineLeakMidrangeTestDiagnostic*/];
	char	cmdWPLLDLineLeak02GPHTestDiagnostic[lenCmd/*lenWPLLDLineLeak02GPHTestDiagnostic*/];
	char	cmdWPLLDLineLeak01GPHTestDiagnostic[lenCmd/*lenWPLLDLineLeak01GPHTestDiagnostic*/];
	char	cmdAccuChartDiagnosticsReport[lenCmd/*lenAccuChartDiagnosticsReport*/];
	char	cmdAccuChartStatusReport[lenCmd/*lenAccuChartStatusReport*/];
	char	cmdAccuChartCalibrationHistoryReport[lenCmd/*lenAccuChartCalibrationHistoryReport*/];
	char	cmdMDIMTotalizerReport[lenCmd/*lenMDIMTotalizerReport*/];
	char	cmdBasicInventoryReconciliationDailyRowReport[lenCmd/*lenBasicInventoryReconciliationDailyRowReport*/];
	char	cmdBasicInventoryReconciliationDailyColumnReport[lenCmd/*lenBasicInventoryReconciliationDailyColumnReport*/];
	char	cmdBasicInventoryReconciliationShiftRowReport[lenCmd/*lenBasicInventoryReconciliationShiftRowReport*/];
	char	cmdBasicInventoryReconciliationShiftColumnReport[lenCmd/*lenBasicInventoryReconciliationShiftColumnReport*/];
	char	cmdBasicInventoryReconciliationPeriodicRowReport106[lenCmd/*lenBasicInventoryReconciliationPeriodicRowReport106*/];
	char	cmdBasicInventoryReconciliationPeriodicColumnReport106[lenCmd/*lenBasicInventoryReconciliationPeriodicColumnReport106*/];
	char	cmdBasicInventoryReconciliationPeriodicRowReport114[lenCmd/*lenBasicInventoryReconciliationPeriodicRowReport114*/];
	char	cmdBasicInventoryReconciliationPeriodicColumnReport114[lenCmd/*lenBasicInventoryReconciliationPeriodicColumnReport114*/];
	char	cmdIndividualBasicReconciliationDailyHistoryDiagnostic[lenCmd/*lenIndividualBasicReconciliationDailyHistoryDiagnostic*/];
	char	cmdPeriodicBookVariance[lenCmd/*lenPeriodicBookVariance*/];
	char	cmdWeeklyBookVariance[lenCmd/*lenWeeklyBookVariance*/];
	char	cmdDailyBookVariance[lenCmd/*lenDailyBookVariance*/];
	char	cmdPeriodicVarianceAnalysisReport[lenCmd/*lenPeriodicVarianceAnalysisReport*/];
	char	cmdWeeklyVarianceAnalysisReport[lenCmd/*lenWeeklyVarianceAnalysisReport*/];
	char	cmdDailyVarianceAnalysisReport[lenCmd/*lenDailyVarianceAnalysisReport*/];
	char	cmdPeriodicVarianceAnalysisDailyReport[lenCmd/*lenPeriodicVarianceAnalysisDailyReport*/];
};

#endif
